server:
  port: 9908

spring:
  application:
    name: miracle-gateway

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  cloud:
    gateway:
      discovery:
        locator:
          # 开启从注册中心动态创建路由的功能，利用微服务名称进行路由
          enabled: true
      routes:
        # 路由的id,没有规定规则但要求唯一,建议配合服务名
        - id: system
          #匹配后提供服务的路由地址
          uri: http://localhost:8099
          predicates:
            # 断言，路径相匹配的进行路由
            - Path=/**

    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

  #redis 配置
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    # 连接超时时间
    timeout: 5s
    lettuce:
      pool:
        max-active: 8   #最大连接数据库连接数,设 0 为没有限制
        max-idle: 8     #最大等待连接中的数量,设 0 为没有限制
        max-wait: -1ms  #最大建立连接等待时间。如果超过此时间将接到异常。设为-1表示无限制。
        min-idle: 0     #最小等待连接中的数量,设 0 为没有限制
#        shutdown-timeout: 400ms


# 全局异常处理：抛出后会被GlobalExceptionHandler.class处理
#mvc:
#  #出现错误时, 直接抛出异常
#  throw-exception-if-no-handler-found: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
  security:
    enabled: false